import io
import unittest

from fun_lib.fasta import read_sequences


class TestReadSequences(unittest.TestCase):

    def test_should_read_sequences(self):
        actual = read_sequences(self.a_fasta_file_content())
        self.assertEqual(actual, [
            'ATGGAGACAGGTACAGTAAAGTGGTTCAATAATGCTAAGGGCTTTGGTTTTATTACCCCAGCAAACGGTGGCGAAGATATTTTTGCCCACTATTCAACAATTAGAATGGAAGGCTACCGCACACTTAAAGCGGGGCAGAAAGTTAATTATAGCACGATAAAAGGGCCTAAAGGTGACCATACTGACCTTATCATTCCTATCATTGAATAG',
            'ATGTCTGACAAAATGAAAGGTCAAGTTAAGTGGTTCAACGAGTCTAAAGGCTTTGGTTTTATTACTCCAGCAGACGGAAGCAAAGACGTATTCGTTCACTTTTCTGCCATTCAAGGTAACGGTTTCAAAACTCTGGCTGAAGGTCAGAACGTAGAATTCACAATTGAAAACGGTGCAAAAGGTCCAGCAGCAGCTAACGTAACAGCTCTGTAA',
            'TTACAGAGCAGTTACGTTAGCAGCTGCTGGACCTTTTGCACCGTTTTCAATTGTGAATTCTACGTTCTGACCTTCAGCCAGAGTTTTGAAACCGTTACCTTGAATGGCAGAAAAGTGAACGAATACGTCTTTGCTTCCGTCTGCTGGAGTAATAAAACCAAAGCCTTTAGACTCGTTGAACCACTTAACTTGACCTTTCATTTTGTCAGACAT']
                         )

    def a_fasta_file_content(self):
        testStream = io.StringIO()
        testStream.write("""
> Proteus_mirabilis_ARLG2970_2781
ATGGAGACAGGTACAGTAAAGTGGTTCAATAATGCTAAGGGCTTTGGTTTTATTACCCCAGCAAACGGTG
GCGAAGATATTTTTGCCCACTATTCAACAATTAGAATGGAAGGCTACCGCACACTTAAAGCGGGGCAGAA
AGTTAATTATAGCACGATAAAAGGGCCTAAAGGTGACCATACTGACCTTATCATTCCTATCATTGAATAG
> Proteus_mirabilis_ARLG2970_0131
ATGTCTGACAAAATGAAAGGTCAAGTTAAGTGGTTCAACGAGTCTAAAGGCTTTGGTTTTATTACTCCAG
CAGACGGAAGCAAAGACGTATTCGTTCACTTTTCTGCCATTCAAGGTAACGGTTTCAAAACTCTGGCTGA
AGGTCAGAACGTAGAATTCACAATTGAAAACGGTGCAAAAGGTCCAGCAGCAGCTAACGTAACAGCTCTG
TAA
> Proteus_penneri_ATCC35198_1543
TTACAGAGCAGTTACGTTAGCAGCTGCTGGACCTTTTGCACCGTTTTCAATTGTGAATTCTACGTTCTGA
CCTTCAGCCAGAGTTTTGAAACCGTTACCTTGAATGGCAGAAAAGTGAACGAATACGTCTTTGCTTCCGT
CTGCTGGAGTAATAAAACCAAAGCCTTTAGACTCGTTGAACCACTTAACTTGACCTTTCATTTTGTCAGA
CAT"""
                         )
        testStream.seek(0)
        return testStream
